### ISSUE TITLE
Error on use npm start

### ISSUE THREAD

**Issue by DrMabuse23** [airtoxin/Electron-React-Boilerplate#1]
Hi thx for your work ,
but i get this error on npm start anny suggestion about this ?

```
Error: ENOENT, no such file or directory '/Users/drmabuse/htdocs/1keyes/build/v0.20.6/darwin-x64/Atom.app/Contents/Resources/app/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/source-map/build/prefix-source-map.jsm'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at fCopyFile (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:275:16)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:304:13)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:285:21)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:285:21)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:285:21)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:285:21)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:285:21)
    at Object.exports.copyDirSyncRecursive (/Users/drmabuse/htdocs/1keyes/node_modules/gulp-atom/node_modules/wrench/lib/wrench.js:285:21)

```

**Comment by airtoxin** [comment]
Hi @DrMabuse23 
In my PC, I can't get such an error on new cloning project.
- You are at wrong directory? (or only renamed atomshell-react-boilerplate?)
- You don't have permission?
