### ISSUE TITLE
Gulp: Error running task sequence: [RangeError: Maximum call stack size exceeded]

### ISSUE THREAD

**Issue by miguelfrde** [airtoxin/Electron-React-Boilerplate#13]
Hi, I'm having this issue when running `npm start`.

My setup is the following:

```
OS: OSX 10.10.5
node: 0.12.7
npm: 2.14.2
global gulp: 3.9.0
```

```
$ npm start

> atomshell-react-boilerplate@0.0.1 start /Users/miguelfrde/Desktop/Electron-React-Boilerplate
> gulp

[11:39:16] Using gulpfile ~/Desktop/Electron-React-Boilerplate/gulpfile.js
[11:39:16] Starting 'watch-compile-build'...
[11:39:16] Finished 'watch-compile-build' after 86 μs
[11:39:16] Starting 'default'...
[11:39:16] Finished 'default' after 23 μs
[11:39:16] Finished 'less' after 62 ms
[11:39:16] Finished 'through' after 77 ms
npm WARN package.json atomshell-react-boilerplate@0.0.1 No README data
[11:39:18] Finished 'install' after 2.04 s
[11:39:18] Finished 'browserify' after 2.27 s
[11:39:18] Starting 'compile'...
[11:39:18] Starting 'atom'...
[11:39:18] gulp-atom-shell electron-v0.30.2-darwin-x64.zip distribute done.
[11:39:22] Finished 'atom' after 3.44 s
[11:39:22] Starting 'build'...
[11:39:22] Starting 'watch-all'...
Error running task sequence: [RangeError: Maximum call stack size exceeded]
[11:39:29] 'watch-all' errored after 7.49 s
[11:39:29] RangeError: Maximum call stack size exceeded
    at Gaze._pollFile (/Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:331:19)
    at /Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:411:12
    at Array.forEach (native)
    at /Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:409:11
    at iterate (/Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/miguelfrde/Desktop/Electron-React-Boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
[11:39:29] Finished 'build' after 2.95 μs
[11:39:29] Finished 'compile' after 13 μs
```

My guess is that what is failing is the watch of the compile directory... But I haven't figured out yet how to fix it.

**Comment by airtoxin** [comment]
set more bigger file descriptor limit.

**Comment by miguelfrde** [comment]
I don't think that's the problem, no matter how big I set `ulimit -n`, the problem persists... and the maximum I can set it to without getting the error `limit: setrlimit failed: invalid argument` is 10240.

**Comment by airtoxin** [comment]
good
