### ISSUE TITLE
npm start throws exception on Windows

### ISSUE THREAD

**Issue by andrerpena** [airtoxin/Electron-React-Boilerplate#19]
I just went into this error while doing `npm start` on Windows 10 using Node.js 0.12...

```
    [05:00:11] Finished 'build' after 2.89 µs
        [05:00:11] Starting 'watch-all'...
        [05:00:15] Finished 'watch-all' after 3.71 s
    events.js:85
    throw er; // Unhandled 'error' event
    ^
    Error: spawn unzip ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! code ELIFECYCLE
    npm ERR! atomshell-react-boilerplate@0.0.1 start: `gulp`
    npm ERR! Exit status 1
```

**Comment by vidbina** [comment]
Hey thanks for pointing that out. From the looks of it [`gulp-atom` uses the `unzip` command](https://github.com/xeodou/gulp-atom/blob/7df9bbf63b303b8f5d6870df466e2e0a2d7fc354/lib/index.js#L111) which probably isn't available from your CLI. Installing WinRAR or WinZIP may get you past the `unzip` problem but isn't the best solution here. A better solution here would be to figure out how to account for all dependencies through the project manifests (`package.json`, etc) :smile: or otherwise clearly document that you need to install a few extra tools :disappointed: when running on Windows.

P.S.: I'd rather fix the manifests which may eventually mean submitting a PR for `gulp-atom` or finding an alternative to `gulp-atom`. Just glanced at the build procedure for a few apps featured on the Electron.js site, observed the `gulp-atom` source and am considering that it may be better to find another way to build the apps. Still looking into it.
