### ISSUE TITLE
npm start error on OSX

### ISSUE THREAD

**Issue by juanpasolano** [airtoxin/Electron-React-Boilerplate#21]
Hi,
I cloned the repo, `npm i` and `npm start` and all i get is this error:

```
> atomshell-react-boilerplate@0.0.1 start /Users/juan/Desktop/Electron-React-Boilerplate
> gulp

[10:35:35] Using gulpfile ~/Desktop/Electron-React-Boilerplate/gulpfile.js
[10:35:35] Starting 'watch-compile-build'...
[10:35:35] Starting 'browserify'...
[10:35:35] Starting 'through'...
[10:35:35] Starting 'less'...
[10:35:35] Starting 'install'...
[10:35:35] Finished 'watch-compile-build' after 94 ms
[10:35:35] Starting 'default'...
[10:35:35] Finished 'default' after 26 μs
[10:35:35] Finished 'less' after 129 ms
[10:35:36] Finished 'through' after 301 ms
loadDep:inflight          ▌ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[10:35:40] Finished 'install' after 4.58 s
[10:35:40] Starting 'compile'...
[10:35:40] Finished 'compile' after 9.87 μs
[10:35:40] Starting 'atom'...
[10:35:40] gulp-atom-shell unzip darwin-x64 v0.30.2 atom-shell.
[10:35:40] Finished 'atom' after 16 ms
[10:35:40] Starting 'build'...
[10:35:40] Finished 'build' after 7.8 μs
[10:35:40] Starting 'watch-all'...
[10:35:42] Finished 'watch-all' after 2.44 s

/Users/juan/Desktop/Electron-React-Boilerplate/node_modules/gulp-atom/lib/index.js:212
      throw new util.PluginError(PLUGIN_NAME, results.stderr || 'unknow error 
            ^
Error: unknow error , maybe you can try delete the zip packages.
    at ChildProcess.<anonymous> (/Users/juan/Desktop/Electron-React-Boilerplate/node_modules/gulp-atom/lib/index.js:212:13)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE
npm ERR! atomshell-react-boilerplate@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atomshell-react-boilerplate@0.0.1 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atomshell-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls atomshell-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juan/Desktop/Electron-React-Boilerplate/npm-debug.log
```

**Comment by evtuhovdo** [comment]
Same error

```
# denisevtuhov at MacBook-Pro-Denis.local in /private/var/www/electron-react on git:master x [12:20:54]
$ npm start                   

> atomshell-react-boilerplate@0.0.1 start /Users/denisevtuhov/www2/electron-react
> gulp

[12:21:04] Using gulpfile ~/www2/electron-react/gulpfile.js
[12:21:04] Starting 'watch-compile-build'...
[12:21:04] Starting 'browserify'...
[12:21:04] Starting 'through'...
[12:21:04] Starting 'less'...
[12:21:04] Starting 'install'...
[12:21:04] Finished 'watch-compile-build' after 48 ms
[12:21:04] Starting 'default'...
[12:21:04] Finished 'default' after 7.46 μs
[12:21:04] Finished 'less' after 60 ms
[12:21:04] Finished 'through' after 135 ms
npm WARN package.json atomshell-react-boilerplate@0.0.1 No README data
[12:21:07] Finished 'browserify' after 2.7 s
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
require-dir@0.3.0 node_modules/require-dir

vinyl-source-stream@1.1.0 node_modules/vinyl-source-stream
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
└── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)

gulp-install@0.4.0 node_modules/gulp-install
├── which@1.2.4 (isexe@1.1.2, is-absolute@0.1.7)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

run-sequence@1.1.5 node_modules/run-sequence
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp@3.9.1 node_modules/gulp
├── interpret@1.0.0
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.1 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.2, findup-sync@0.3.0, resolve@1.1.7)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-atom@0.1.0 node_modules/gulp-atom
├── progress@1.1.8
├── async@0.9.2
├── wrench@1.5.9
├── semver@4.3.6
├── vinyl@0.2.3 (clone-stats@0.0.1)
├── through2@0.4.2 (readable-stream@1.0.33, xtend@2.1.2)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)
└── grs@0.1.3 (highland@1.29.0, JSONStream@0.8.4, request@2.70.0)

reactify@1.1.1 node_modules/reactify
├── through@2.3.8
└── react-tools@0.13.3 (jstransform@10.1.0, commoner@0.10.4)

react@0.14.8 node_modules/react
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
└── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.1.0, promise@7.1.1, core-js@1.2.6)

browserify@11.2.0 node_modules/browserify
├── https-browserify@0.0.1
├── tty-browserify@0.0.0
├── path-browserify@0.0.0
├── constants-browserify@0.0.1
├── punycode@1.4.1
├── builtins@0.0.7
├── string_decoder@0.10.31
├── browser-resolve@1.11.1
├── isarray@0.0.1
├── os-browserify@0.1.2
├── inherits@2.0.1
├── htmlescape@1.1.1
├── process@0.11.2
├── commondir@0.0.1
├── stream-browserify@2.0.1
├── assert@1.3.0
├── shell-quote@0.0.1
├── defined@1.0.0
├── domain-browser@1.1.7
├── xtend@4.0.1
├── querystring-es3@0.2.1
├── timers-browserify@1.4.2
├── util@0.10.3
├── deps-sort@1.3.9
├── events@1.0.2
├── parents@1.0.1 (path-platform@0.11.15)
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── has@1.0.1 (function-bind@1.1.0)
├── readable-stream@2.0.6 (process-nextick-args@1.0.6, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── url@0.10.3 (punycode@1.3.2, querystring@0.2.0)
├── subarg@1.0.0 (minimist@1.2.0)
├── through2@1.1.1 (readable-stream@1.1.13)
├── duplexer2@0.0.2 (readable-stream@1.1.13)
├── concat-stream@1.4.10 (typedarray@0.0.6, readable-stream@1.1.13)
├── buffer@3.6.0 (ieee754@1.1.6, isarray@1.0.0, base64-js@0.0.8)
├── read-only-stream@1.1.1 (readable-wrap@1.0.0, readable-stream@1.1.13)
├── stream-http@1.7.1 (indexof@0.0.1, builtin-status-codes@1.0.0, foreach@2.0.5, object-keys@1.0.9)
├── JSONStream@1.1.1 (through@2.3.8, jsonparse@1.2.0)
├── glob@4.5.3 (once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── shasum@1.0.2 (sha.js@2.4.5, json-stable-stringify@0.0.1)
├── resolve@1.1.7
├── browserify-zlib@0.1.4 (pako@0.2.8)
├── syntax-error@1.1.6 (acorn@2.7.0)
├── browser-pack@5.0.1 (umd@3.0.1, combine-source-map@0.6.1)
├── labeled-stream-splicer@1.0.2 (stream-splicer@1.3.2)
├── crypto-browserify@3.11.0 (create-hmac@1.1.4, randombytes@2.0.3, pbkdf2@3.0.4, create-hash@1.1.2, diffie-hellman@5.0.2, create-ecdh@4.0.0, browserify-cipher@1.0.0, public-encrypt@4.0.0, browserify-sign@4.0.0)
├── insert-module-globals@6.6.3 (is-buffer@1.1.3, combine-source-map@0.6.1, lexical-scope@1.2.0)
└── module-deps@3.9.1 (readable-stream@1.1.13, detective@4.3.1, stream-combiner2@1.0.2)

gulp-less@3.0.5 node_modules/gulp-less
├── object-assign@4.0.1
├── vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.3)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.12)
├── accord@0.20.5 (indx@0.2.3, convert-source-map@1.2.0, semver@4.3.6, fobject@0.0.3, glob@5.0.15, when@3.7.7, resolve@1.1.7, uglify-js@2.6.2, lodash@3.10.1)
└── less@2.6.1 (graceful-fs@4.1.3, mime@1.3.4, image-size@0.4.0, source-map@0.5.3, mkdirp@0.5.1, promise@7.1.1, errno@0.1.4, request@2.70.0)
[12:21:46] Finished 'install' after 42 s
[12:21:46] Starting 'compile'...
[12:21:46] Finished 'compile' after 15 μs
[12:21:46] Starting 'atom'...
[12:21:46] Finished 'atom' after 20 ms
[12:21:46] Starting 'build'...
[12:21:46] Finished 'build' after 28 μs
[12:21:46] Starting 'watch-all'...
[12:21:49] Finished 'watch-all' after 2.57 s
[12:21:52] gulp-atom-shell unzip darwin-x64 v0.30.2 atom-shell.

/Users/denisevtuhov/www2/electron-react/node_modules/gulp-atom/lib/index.js:212
      throw new util.PluginError(PLUGIN_NAME, results.stderr || 'unknow error , maybe you can try delete the zip packages.');
      ^
Error:   End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/denisevtuhov/www2/electron-react/cache/v0.30.2/electron-v0.30.2-darwin-x64.zip or
        /Users/denisevtuhov/www2/electron-react/cache/v0.30.2/electron-v0.30.2-darwin-x64.zip.zip, and cannot find /Users/denisevtuhov/www2/electron-react/cache/v0.30.2/electron-v0.30.2-darwin-x64.zip.ZIP, period.

    at ChildProcess.<anonymous> (/Users/denisevtuhov/www2/electron-react/node_modules/gulp-atom/lib/index.js:212:13)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! atomshell-react-boilerplate@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atomshell-react-boilerplate@0.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the atomshell-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls atomshell-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/denisevtuhov/www2/electron-react/npm-debug.log
```
