### ISSUE TITLE
React code vs. esperanto

### ISSUE THREAD

**Issue by apreg** [airtoxin/Electron-React-Boilerplate#9]
I've tried to put this simple file under app/components/

```
"use strict";
var React = require('react');

var Main = React.createClass( {
    displayName: 'Main',
    render: function() {
        return (
        <div>
                <p>main content</p>
            </div>
        );
    }
} );

export default Main;
```

but the start fails with this error:

``````
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unexpected token (8:2) c:\WORKSPACE\JS\electron-boilerplate\app\components\Main.js
    at c:\WORKSPACE\JS\electron-boilerplate\tasks\build.js:59:19
    at map (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\index.js:38:20)
    at Transform.write [as _transform] (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\index.js:19:33)
    at Transform._read (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Transform.Writable.write (c:\WORKSPACE\JS\electron-boilerplate\node_modules\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (c:\WORKSPACE\JS\electron-boilerplate\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (c:\WORKSPACE\JS\electron-boilerplate\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)```

In line 8 there is the <div> html tag.
``````

**Comment by apreg** [comment]
Please delete this issue. I've opened it in a wrong repository. Sorry.
